name: Fetch and Store Odds

on:
  workflow_dispatch:  # Allows manual run
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run odds fetcher
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python fetch_and_store_odds.py
